### ISSUE TITLE
emoji表情问题

### ISSUE THREAD

**Issue by leiwei1991** [wangsijie/pomelo-weixin-client#1]
我用的是单文件版，两个人在一个聊天室，一个人发了一个表情，另一个人收到的还是乱码。

**Comment by leiwei1991** [comment]
服务端pomelo源码收到消息体buffer处理是用msg.body.toString('utf-8')，这种方式直接会变成乱码，参照protocol.strdecode方式对msg.body进行处理，修改源码问题解决了。

有没有其他方式解决这个问题？

**Comment by wangsijie** [comment]
@leiwei1991 参见这个PR [https://github.com/NetEase/pomelo/pull/1093](https://github.com/NetEase/pomelo/pull/1093)，就是用类似的方法处理

官方似乎放弃对pomelo的维护了

**Comment by xiaobear250** [comment]
@leiwei1991 你好，可以说得更清楚一点吗？我客户端是小程序，服务端pomelo，小程序自身发表情展示没问题，但是经过pomelo服务端转发就会变成乱码。
你说的是把pomelo/lib/connectors/common/coder.js里面39行的
` msg.body = JSON.parse(msg.body.toString('utf8'));`
改为
` msg.body = JSON.parse(protocol.strdecode(msg.body));`
吗？
我试了好像没用。。。

**Comment by wangsijie** [comment]
@xiaobear250 看我上面给pomolo的PR的代码 [https://github.com/NetEase/pomelo/pull/1093/commits/29bc58e63704464ca832d404369aa7854769260d](https://github.com/NetEase/pomelo/pull/1093/commits/29bc58e63704464ca832d404369aa7854769260d)

**Comment by xiaobear250** [comment]
@wangsijie 看了，不过他针对的是网页的，而我用的是您这边这个pomelo-weixin-client，两者应该不太一样吧？如果是要我理会其中的原理再去更改，那我暂时还没那个水平。。。
我研究了下，pomelo-weixin-client/src/Protocal.js中的strdecode函数应该是对应上述PR代码修改的部分，于是我狗尾续貂把pomelo-weixin-client里面的内容改成了以下：
          var bytes = new Uint8Array(e);
          var array = [];
          var offset = 0;
          var charCode = 0;
          var end = bytes.length;
          while (offset < end) {
            if (bytes[offset] < 128) {
              charCode = bytes[offset];
              offset += 1;
            } else if (bytes[offset] < 224) {
              charCode = ((bytes[offset] & 0x3f) << 6) + (bytes[offset + 1] & 0x3f);
              offset += 2;
            } else if (bytes[offset] < 240) {
              charCode = ((bytes[offset] & 0x0f) << 12) + ((bytes[offset + 1] & 0x3f) << 6) + (bytes[offset + 2] & 0x3f);
              offset += 3;
            } else if (bytes[offset] < 256) {
              charCode = ((bytes[offset] & 0x07) << 18) + ((bytes[offset + 1] & 0x3f) << 12) + ((bytes[offset + 2] & 0x3f) << 6) + (bytes[offset + 3] & 0x3f);
              offset += 4;
            }
            array.push(charCode);
          }
          var codeToString = String.fromCodePoint || String.fromCharCode;
          var res = '';
          var chunk = 8 * 1024;
          var i;
          for (i = 0; i < array.length / chunk; i++) {
            res += codeToString.apply(null, array.slice(i * chunk, (i + 1) * chunk));
          }
          res += codeToString.apply(null, array.slice(i * chunk));
          return res;

貌似还是不行。。。

**Comment by wangsijie** [comment]
@xiaobear250 客户端（pomelo-weixin-client）的最新版本身已经支持emoji的接收，请升级到最新版。如果要经过服务端中转，需要把这个pr代码自己合并后打包一个pomelo

**Comment by leiwei1991** [comment]
@xiaobear250  msg.body = JSON.parse(protocol.strdecode(msg.body));  我修改的也是这个地方，只是这个strdecode用的是pomelo-weixin-client/src/Protocal.js中的strdecode。直接在pomelo/lib/connectors/common/coder.js里添加了这个函数，你自己试下。

**Comment by xiaobear250** [comment]
@leiwei1991 @wangsijie 
一不做二不休，我把pomelo-protocol里面的strdecode也改了，貌似可以用。
问题解决了，谢谢两位。
做个记录：
1、客户端用最新版的pomelo-weixin-client，已经支持emoji接收。
2、服务端pomelo改造：
（1）pomelo/lib/connectors/common/coder.js
前面添加var protocol = require('pomelo-protocol');
原39行改为：msg.body = JSON.parse(protocol.strdecode(msg.body));
（2）pomelo-protocol/lib/protocol.js
70行开始的strdecode函数改为：
Protocol.strdecode = function(buffer) {
    var bytes = new Uint8Array(buffer);
    var array = [];
    var offset = 0;
    var charCode = 0;
    var end = bytes.length;
    while (offset < end) {
        if (bytes[offset] < 128) {
            charCode = bytes[offset];
            offset += 1;
        } else if (bytes[offset] < 224) {
            charCode = ((bytes[offset] & 0x3f) << 6) + (bytes[offset + 1] & 0x3f);
            offset += 2;
        } else if (bytes[offset] < 240) {
            charCode = ((bytes[offset] & 0x0f) << 12) + ((bytes[offset + 1] & 0x3f) << 6) + (bytes[offset + 2] & 0x3f);
            offset += 3;
        } else if (bytes[offset] < 256) {
            charCode = ((bytes[offset] & 0x07) << 18) + ((bytes[offset + 1] & 0x3f) << 12) + ((bytes[offset + 2] & 0x3f) << 6) + (bytes[offset + 3] & 0x3f);
            offset += 4;
        }
        array.push(charCode);
    }
    return String.fromCodePoint ? String.fromCodePoint.apply(null, array) : String.fromCharCode.apply(null, array);
  };
以上。
