### ISSUE TITLE
是否可以增加对没有module.exports环境的兼容？

### ISSUE THREAD

**Issue by hk86s** [wangsijie/pomelo-weixin-client#4]
例如：LAYA或EGRET的项目，使用的TS文件，在这样的非NODE环境下，是没有module.exports的概念的。希望可以提供一个全局的对象，或者通过任意合理的方式提供pomelo及Pomelo的属性访问。
如果能增加d.ts就更好了。
当前自定义的修改方式是将合并后的js的第一行
var pomelo,Pomelo;!function(e,t){pomelo=t(),Pomelo=pomelo.constructor;}

**Comment by hk86s** [comment]
原始：
!function(e,t){"object"==typeof exports&&"object"==typeof module?module.exports=t():"function"==typeof define&&define.amd?define([],t):"object"==typeof exports?exports.pomelo=t():e.pomelo=t()}
修改：
var pomelo,Pomelo;!function(e,t){pomelo=t(),Pomelo=pomelo.constructor;}
但这样无法和官方的更新同步了，需要每次都修改。


ps:如果能增加d.ts就更好了。非刚需，自己实现工作量不大。

**Comment by wangsijie** [comment]
不了解EGRET，但打包方式的最后处理，是将pomelo注入全局this中，例如，在浏览器里，this就是window，因此直接调用 pomelo 即可（即相当于全局变量的作用）。 见以下代码的倒数第二行。不知EGRET等项目的顶级this是什么？
```js
!function(e, t) {
    "object" == typeof exports && "object" == typeof module
      ? (module.exports = t())
      : "function" == typeof define && define.amd
        ? define("pomelo", [], t)
        : "object" == typeof exports
          ? (exports.pomelo = t())
          : (e.pomelo = t());
  };
```
注：e是全局this，见接下来的代码调用`(this,function(){return function(e){var...`

**Comment by wy19910222** [comment]
> 不了解EGRET，但打包方式的最后处理，是将pomelo注入全局this中，例如，在浏览器里，this就是window，因此直接调用 pomelo 即可（即相当于全局变量的作用）。 见以下代码的倒数第二行。不知EGRET等项目的顶级this是什么？
> 
> ```js
> !function(e, t) {
>     "object" == typeof exports && "object" == typeof module
>       ? (module.exports = t())
>       : "function" == typeof define && define.amd
>         ? define("pomelo", [], t)
>         : "object" == typeof exports
>           ? (exports.pomelo = t())
>           : (e.pomelo = t());
>   };
> ```
> 
> 注：e是全局this，见接下来的代码调用`(this,function(){return function(e){var...`

我来解释一下hk86s的意思：
在LayaAir引擎中，环境是浏览器环境，没有node环境，所以没有module.exports，所有js文件靠index.html引用，相当于所有代码集中在一个js中，发布为微信小游戏，也是把所有代码合并成一个code.js。
也就是说，使用LayaAir引擎，在代码编辑和调试过程中，都是没有module.exports的，所以：
```
    "object" == typeof exports && "object" == typeof module
      ? (module.exports = t())
      : "function" == typeof define && define.amd
        ? define("pomelo", [], t)
        : "object" == typeof exports
          ? (exports.pomelo = t())
          : (e.pomelo = t());
```
这段代码执行的是最后一行：
```
e.pomelo = t()
```
但是当发布为微信小游戏后，微信环境中存在module，所以执行的是：
```
module.exports = t()
```
这导致代码编辑环境和实际运行环境执行不同的逻辑，那么使用pomelo就会很不方便。
如果不改pomelo代码，那么似乎只有这么一种合适的方案：
1.因为编辑环境中需要用pomelo测试，所以需要在html里引用pomelo-wexin-client.js，这导致代码会被合并到最终的code.js里。
2.因为微信环境中需要用pomelo运行，所以需要额外在外部放一份pomelo-wexin-client.js，通过require引入pomelo。
这样会存在两份pomelo-wexin-client.js的代码。

理想的方案是，即使存在module，也可以让使用者选择到底是执行module.exports = t()还是e.pomelo = t()，这样，两边的环境都可以选择执行e.pomelo = t()，从而解决这个问题。

**Comment by wangsijie** [comment]
可以在引入前定义或者凡定义module

> > 不了解EGRET，但打包方式的最后处理，是将pomelo注入全局this中，例如，在浏览器里，this就是window，因此直接调用 pomelo 即可（即相当于全局变量的作用）。 见以下代码的倒数第二行。不知EGRET等项目的顶级this是什么？
> > ```js
> > !function(e, t) {
> >     "object" == typeof exports && "object" == typeof module
> >       ? (module.exports = t())
> >       : "function" == typeof define && define.amd
> >         ? define("pomelo", [], t)
> >         : "object" == typeof exports
> >           ? (exports.pomelo = t())
> >           : (e.pomelo = t());
> >   };
> > ```
> > 
> > 
> > 注：e是全局this，见接下来的代码调用`(this,function(){return function(e){var...`
> 
> 我来解释一下hk86s的意思：
> 在LayaAir引擎中，环境是浏览器环境，没有node环境，所以没有module.exports，所有js文件靠index.html引用，相当于所有代码集中在一个js中，发布为微信小游戏，也是把所有代码合并成一个code.js。
> 也就是说，使用LayaAir引擎，在代码编辑和调试过程中，都是没有module.exports的，所以：
> 
> ```
>     "object" == typeof exports && "object" == typeof module
>       ? (module.exports = t())
>       : "function" == typeof define && define.amd
>         ? define("pomelo", [], t)
>         : "object" == typeof exports
>           ? (exports.pomelo = t())
>           : (e.pomelo = t());
> ```
> 这段代码执行的是最后一行：
> 
> ```
> e.pomelo = t()
> ```
> 但是当发布为微信小游戏后，微信环境中存在module，所以执行的是：
> 
> ```
> module.exports = t()
> ```
> 这导致代码编辑环境和实际运行环境执行不同的逻辑，那么使用pomelo就会很不方便。
> 如果不改pomelo代码，那么似乎只有这么一种合适的方案：
> 1.因为编辑环境中需要用pomelo测试，所以需要在html里引用pomelo-wexin-client.js，这导致代码会被合并到最终的code.js里。
> 2.因为微信环境中需要用pomelo运行，所以需要额外在外部放一份pomelo-wexin-client.js，通过require引入pomelo。
> 这样会存在两份pomelo-wexin-client.js的代码。
> 
> 理想的方案是，即使存在module，也可以让使用者选择到底是执行module.exports = t()还是e.pomelo = t()，这样，两边的环境都可以选择执行e.pomelo = t()，从而解决这个问题。
