### ISSUE TITLE
建议针对服务端推送消息新增统一emit

### ISSUE THREAD

**Issue by wy19910222** [wangsijie/pomelo-weixin-client#6]
Pomelo.js文件第287-290行：
```
        if (!msg.id) {
            this.emit(msg.route, msg.body);
            return;
        }
```
客户端对服务端推送的消息，需要事先知道route才能监听到，而我在调试时，希望有一个统一的地方能打印所有服务端推送过来的消息。所以希望服务端推送消息有一个统一emit，想要分开监听的使用者可以在外部自己分开emit。

建议：
第287-290行改为：
```
        if (!msg.id) {
            this.emit(“onPush”, msg.route, msg.body);
            this.emit(msg.route, msg.body);
            return;
        }
```
这么建议的另一个原因：
其他的emit的event全是固定的事件类型，而this.emit(msg.route, msg.body);却把route作为事件类型，虽然换个思路理解也可以认为推送过来的route就是事件类型，但是感觉不够统一。

**Comment by wangsijie** [comment]
起名为 onMessage

**Comment by wy19910222** [comment]
好的
